# Generated by Django 5.1.6 on 2025-03-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_job_employee_alter_services_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
