# Generated by Django 5.1.6 on 2025-03-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_job_info_job_total_price_job_vat_alter_job_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
