# Generated by Django 5.1.6 on 2025-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_rename_process_date_job_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
