# Generated by Django 5.1.6 on 2025-03-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_job_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('in_progress', 'İşlemde'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal')], default='pending', max_length=20),
        ),
    ]
