# Generated by Django 5.1.6 on 2025-03-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
