# Generated by Django 5.1.6 on 2025-03-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_job_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
